# ---------------------------------
# |    KOOK Bot | KOOK 机器人      |
# ---------------------------------
# 此插件是受EssentialsXDiscord的灵感，接入KOOK的机器人通讯插件！
# 目前处于开发阶段，欢迎PR和提Issues！https://github.com/littlekan233/KOOKBot
# 创建KOOK机器人？点击此链接->https://developer.kookapp.cn/app/index

# 你需要填写token才能正常使用机器人
token: "y0uR_7okEN"

# 你必须连接一个M...啊呸，KOOK服务器的频道
# 打开开发者工具后，右键频道和服务器复制ID！
# 服务器ID用于绑定功能关联用户
# 频道ID用于消息处理
kook_server_id: "0001145141919810"
kook_channel_id: "0001145141919810"

# 邀请链接来一套~
# 在输入命令 /kook invite 时显示~
invite_url: "https://kook.top/Y0urS3rv3R"

# 你需要设定一下发送信息格式（谁愿意见到丑陋的聊天信息啊喂）
chat_format:
  # MC服务器→KOOK服务器
  kook: "[{display_name}] {message}"
  # KOOK服务器→MC服务器
  mc: "&a[KOOK] &6{kook_name}&l({mc_name}) &7>> &f&r{message}"
  # 占位符：
  # {display_name}  仅MC->KOOK  显示名，先获取绑定信息然后@出来，如果未绑定无法发送 显示格式：@mykookuser<mymcname>
  # {kook_name}  仅KOOK->MC  KOOK昵称（不是服务器内昵称！）
  # {mc_name}  仅KOOK->MC  在MC显示的用户名（非MC里的nick！）
  # {message}  两种都适用  【必须要！否则插件将因为不存在此占位符而禁用！】显示的信息
  # ** MC->KOOK目前不支持颜色！！！！ **