name: KOOKBot
version: '${project.version}'
author: "littlekan233"
main: ml.littlekan.kookbot.KOOKBot
api-version: '1.13'
commands: 
  kook:
    description: "KOOKBot 主命令"
    usage: "/kook [invite|help|link|send <message>]"